name: Apply_infrastructure for API
on:
  push:
    branches:
      - feature/DD-46-API_GW
  pull_request:
    branches:
      - feature/DD-46-API_GW

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_AK }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_AK }}
      TF_GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
      AWS_REGION: us-east-1 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.6
    
      - name: Configure AWS Credentials
        run: echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_AK}" >> $GITHUB_ENV && echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_AK}" >> $GITHUB_ENV
      
      - name: Initialize terraform
        run: terraform init 
      
      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Plan
        run: terraform plan -out=tfplan
      
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
