name: Terraform-Github-Destroy

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }} # Custom secret name for GitHub token

    steps:
      - name: Show AWS Identity
        run: aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init 
        
      - name: Show Destroy plan
        run: terraform plan -destroy
    
      - name: Terraform destroy
        run: terraform destroy -auto-approve
