name: Terraform_Apply_Code

on:
  workflow_dispatch:
  pull_request:
    branches:
      - development

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VERSION: 1.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        run: |
          echo "AWS_IAM_ROLE_TO_ASSUME=${{ secrets.AWS_IAM_ROLE_TO_ASSUME }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform   # Specify the working directory
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
