name: Kubernetes Ingress Controller Deployment

on:
  push:
    branches:
      - feature/DD-46-API_GW

jobs:
  deploy-ingress-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init -upgrade=true
      
      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Plan
        run: terraform plan -out=tfplan
      
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan    
