name: Terraform Destroy
on:
  workflow_dispatch:
  push:
    branches:
      - development

jobs:
  tf-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-west-1'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Terraform                                                                      
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init
        env:
          TF_LOG: DEBUG

      - name: Show Terraform Version
        run: terraform version

      - name: List Terraform Files
        run: ls -l

      - name: Validate Terraform Configuration
        run: terraform validate
        continue-on-error: true
        env:
          TF_LOG: DEBUG

      - name: Show Destroy Plan
        id: plan
        run: terraform plan -destroy
        continue-on-error: true
        env:
          TF_LOG: DEBUG

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
        env:
          TF_LOG: DEBUG

      - name: Post-Destroy Check
        run: terraform state list || echo "No resources found"
        env:
          TF_LOG: DEBUG
